spring.application.name=cadastroclientes
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
logging.level.org.springframework.jdbc.core=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_SECRET_EXPIRATION_MS}

admin.default.email=${ADMIN_DEFAULT_EMAIL}
admin.default.senha=${ADMIN_DEFAULT_PASSOWRD}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}