spring.application.name=cadastroclientes
spring.datasource.url=datasource_url
spring.datasource.username=datasource_username
spring.datasource.password=datasource_password

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
logging.level.org.springframework.jdbc.core=DEBUG

jwt.secret=token_jwt_key
jwt.expiration-ms=token_jwt_expiration

admin.default.email=admin_email
admin.default.senha=admin_password

n8n.webhook.url=url_webhook
n8n.webhook.secret=webhook_secret_key
admin.notificacao.email=email.example.com