spring.application.name=cadastroclientes
spring.datasource.url=jdbc:postgresql://localhost:5432/cadastroclientes
spring.datasource.username=brenno
spring.datasource.password=Br3nno1106.

spring.sql.init.mode=always
