CREATE TABLE produto (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_de_barras        VARCHAR2(255) NOT NULL UNIQUE,
    nome                    VARCHAR2(255) NOT NULL,
    preco                   NUMBER(10,2) NOT NULL,
    quantidade_em_estoque   NUMBER NOT NULL,
    data_criacao            TIMESTAMP,
    data_ultima_atualizacao TIMESTAMP
);