CREATE TABLE compra (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_compra TIMESTAMP,
    cliente_id  NUMBER NOT NULL REFERENCES usuarios (id),
    valor_total NUMBER(10,2)
);